package Exceptions;

public class ExceptionInClass {
	
	public void testMethod() throws Exception
	{
		//try
		{
			int a = 5/0;
		}
	/*
	catch(Exception e){
		System.out.println("inside exception in ExceptionInClass:::"+e);
		
	}*/
	
	}

}
